-- 创建alerts表
CREATE TABLE alerts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  signal_id bigint REFERENCES signals(id),
  alert_type text NOT NULL DEFAULT '系统',
  status text NOT NULL DEFAULT '已记录',
  message text NOT NULL,
  email text,
  email_status text,
  created_at timestamp with time zone DEFAULT now()
);

-- 创建索引
CREATE INDEX idx_alerts_signal_id ON alerts(signal_id);
CREATE INDEX idx_alerts_created_at ON alerts(created_at);
